[tool.poetry]
name = "variant_alert"
version = "0.1.0"
description = "Compare two clinvar VCF version and output differences of classification between gene and variants. Can also generate a clinvarome file."
authors = [
  "Mélanie Broutin <melanie.broutin@seqone.fr>",
  "Abdoulaye Diallo <abdoulaye.diallo@seqone.fr>",
  "Raphaël Lanos <raphael.lanos@seqone.fr>",
  "Kévin Yauy <kevin.yauy@seqone.fr>"
]

[tool.poetry.dependencies]
python = "^3.8"
pysam = "^0.22.0"
click = "^8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
pytest-cov = "^4.0"
flake8 = "^6.0"
black = "^23.0"

[tool.poetry.scripts]
variant-alert = "variant_alert.cli:variant_alert"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
